name: 📘 Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: input
    attributes:
      label: Page or section
      placeholder: README / users-guide / schema field / example name
    validations:
      required: true

  - type: textarea
    attributes:
      label: What’s unclear or incorrect?
      description: Describe the issue or confusion.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested improvement (optional)
      description: How would you improve it?

