apiVersion: modelspec.paralleliq.ai/v0.1
kind: ModelSpec

metadata:
  name: rag-llm
  labels:
    pattern: rag

spec:
  identity:
    model:
      id: qwen2.5-7b-instruct
      family: qwen2.5
      task: text-generation
      framework: transformers

  runtime:
    accelerator:
      vendor: nvidia
      type: a100-80gb
      count: 1

  dependencies:
    - id: embedder
      role: input                       # Semantic role in the system
      specRef: ./embedder.modelspec.yaml
      required: true
      interface:
        inputType: text
        outputType: embedding
        maxLatencyMs: 50                # Dependency SLO

    - id: reranker
      role: rank
      specRef: ./reranker.modelspec.yaml
      required: false
      interface:
        inputType: text+documents
        outputType: ranked_documents
        maxLatencyMs: 80
